### ISSUE TITLE
Not able to use map_tasks in new workflow

### ISSUE THREAD

**Issue by jvfe** [latchbio/latch#158]
Hi,
I'm not able to use map_tasks in my new workflow, using latch **v.1.17.1**. Here's the workflow code: https://github.com/jvfe/pangolin_latch. Even though the workflow registers fine, when I go to run it, it raises a flytekit error:

<details>
<summary> See stack trace </summary>

```
Traceback (most recent call last):
  File "/opt/conda/bin/pyflyte-map-execute", line 8, in <module>
    sys.exit(map_execute_task_cmd())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/flytekit/bin/entrypoint.py", line 525, in map_execute_task_cmd
    _execute_map_task(
  File "/opt/conda/lib/python3.9/site-packages/flytekit/exceptions/scopes.py", line 160, in system_entry_point
    return wrapped(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/flytekit/bin/entrypoint.py", line 376, in _execute_map_task
    raise Exception("Map tasks cannot be run with instance tasks.")
Exception: Map tasks cannot be run with instance tasks.
```

</details>

"Exception: Map tasks cannot be run with instance tasks.". The error persists when using small_tasks too.

**Comment by ayushkamat** [comment]
Your workflow is also called pangolin, so what you're actually doing is calling map_task on a workflow. This is a user error, so I'm closing this.
