### ISSUE TITLE
Local execution fails if remote paths are included

### ISSUE THREAD

**Issue by jvfe** [latchbio/latch#79]
- **Docker version**: 20.10.16
- **Python version**: 3.10.4
- **Latch SDK version**: 1.1.0

I was trying to build a simple workflow and test it locally but came by some errors when I tried the `latch local-execute` command. I noticed the errors only occur when I include the remote paths in the return statements of each task. I'm not sure if this is the intended behavior, as [in the documentation](https://docs.latch.bio/basics/local_development.html) the example still states the remote path and says that "there will be no attempt to copy data from remote paths when ingesting or returning parameter values". The issue seems to be that latch still tries to copy the remote data even when executing locally.

I built a minimal reproducible example that should raise the error. It uses the same Dockerfile and data as in the default boilerplate.

<details>
<summary>See example</summary>

If the remote path argument is removed from both task return statements, the error doesn't happen.

```py
from pathlib import Path

from latch import small_task, workflow
from latch.types import LatchFile


@small_task
def foo(a: LatchFile) -> LatchFile:

    with open(a) as f:
        a_text = f.read()

    b = Path("new.txt").resolve()
    with open(b, "w") as f:
        f.write(a_text)

    return LatchFile(str(b), "latch:///remote_location/a.txt")


@small_task
def bar(b: LatchFile) -> LatchFile:

    with open(b) as f:
        print(f.read())

    c = Path("new2.txt").resolve()
    with open(c, "w") as f:
        f.write("somenewtext again")

    return LatchFile(str(c), "latch:///remote_location/c.txt")


@workflow
def foobar(a: LatchFile) -> LatchFile:
    """
    ...
    """
    foo_res = foo(a=a)
    return bar(b=foo_res)


if __name__ == "__main__":
    foobar(
        a=LatchFile("/root/reference/wuhan.fasta"),
    )
```

</details>
 
<details>
<summary>See error logs</summary>

```
Spinning up local container...
NOTE ~ workflow code is bound as a mount.
You must register your workflow to persist changes.

Streaming stdout from registered container running locally
{"asctime": "2022-06-07 16:39:29,955", "name": "flytekit", "levelname": "WARNING", "message": "Running pod task locally. Local environment may not match pod environment which may cause issues."}

LATCH_ENDPOINT: https://nucleus.latch.bio

{"asctime": "2022-06-07 16:39:30,736", "name": "flytekit", "levelname": "ERROR", "message": "Failed to convert return value for var o0 with error <class 'flytekit.exceptions.user.FlyteAssertion'>: Failed to put data from /root/new.txt to latch:///remote_location/a.txt (recursive=False).\n\nOriginal exception: failed to get presigned upload urls for `latch:///remote_location/a.txt`"}

Traceback (most recent call last):

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/data_persistence.py", line 443, in put_data

		  DataPersistencePlugins.find_plugin(remote_path)().put(local_path, remote_path, recursive=is_multipart)

		File "/usr/local/lib/python3.9/site-packages/flytekit/extras/persistence/latch.py", line 243, in put

		  return self.upload(from_path, to_path)

		File "/usr/local/lib/python3.9/site-packages/flytekit/extras/persistence/latch.py", line 190, in upload

		  return LatchPersistence._upload(file_path, to_path, self._chunk_size, self._latch_endpoint)

		File "/usr/local/lib/python3.9/site-packages/flytekit/extras/persistence/latch.py", line 162, in _upload

		  raise FlyteUserException("failed to get presigned upload urls for `{}`".format(to_path))

flytekit.exceptions.user.FlyteUserException: failed to get presigned upload urls for `latch:///remote_location/a.txt`



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/base_task.py", line 524, in dispatch_execute

		  literals[k] = TypeEngine.to_literal(exec_ctx, v, py_type, literal_type)

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/type_engine.py", line 798, in to_literal

		  lv = transformer.to_literal(ctx, python_val, python_type, expected)

		File "/usr/local/lib/python3.9/site-packages/flytekit/types/file/file.py", line 327, in to_literal

		  ctx.file_access.put_data(source_path, remote_path, is_multipart=False)

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/data_persistence.py", line 445, in put_data

		  raise FlyteAssertion(

flytekit.exceptions.user.FlyteAssertion: Failed to put data from /root/new.txt to latch:///remote_location/a.txt (recursive=False).



Original exception: failed to get presigned upload urls for `latch:///remote_location/a.txt`



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

		File "/root/wf/__init__.py", line 43, in <module>

		  foobar(

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/workflow.py", line 238, in __call__

		  return flyte_entity_call_handler(self, *args, **input_kwargs)

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/promise.py", line 1002, in flyte_entity_call_handler

		  result = cast(LocallyExecutable, entity).local_execute(child_ctx, **kwargs)

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/workflow.py", line 253, in local_execute

		  function_outputs = self.execute(**kwargs)

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/workflow.py", line 686, in execute

		  return exception_scopes.user_entry_point(self._workflow_function)(**kwargs)

		File "/usr/local/lib/python3.9/site-packages/flytekit/exceptions/scopes.py", line 198, in user_entry_point

		  return wrapped(*args, **kwargs)

		File "/root/wf/__init__.py", line 38, in foobar

		  foo_res = foo(a=a)

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/base_task.py", line 284, in __call__

		  return flyte_entity_call_handler(self, *args, **kwargs)

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/promise.py", line 995, in flyte_entity_call_handler

		  return cast(LocallyExecutable, entity).local_execute(ctx, **kwargs)

		File "/usr/local/lib/python3.9/site-packages/flytekitplugins/pod/task.py", line 128, in local_execute

		  return super().local_execute(ctx=ctx, **kwargs)

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/base_task.py", line 265, in local_execute

		  outputs_literal_map = self.dispatch_execute(ctx, input_literal_map)

		File "/usr/local/lib/python3.9/site-packages/flytekit/core/base_task.py", line 527, in dispatch_execute

		  raise TypeError(

TypeError: Failed to convert return value for var o0 for function foo with error <class 'flytekit.exceptions.user.FlyteAssertion'>: Failed to put data from /root/new.txt to latch:///remote_location/a.txt (recursive=False).



Original exception: failed to get presigned upload urls for `latch:///remote_location/a.txt`
```
</details>

**Comment by mnemeth66** [comment]
does this actually prevent the wf for running for you?

**Comment by jvfe** [comment]
As an update, I just tried the same example I've given above in version 1.15.0 and now it doesn't work with or without the remote paths. Raising a whole new error:

<details>
<summary> See error log </summary>

```
Traceback (most recent call last):
  File "/home/jvfe/dev/latchbio/.venv/bin/latch", line 8, in <module>
    sys.exit(main())
  File "/home/jvfe/dev/latchbio/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jvfe/dev/latchbio/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jvfe/dev/latchbio/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jvfe/dev/latchbio/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jvfe/dev/latchbio/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jvfe/dev/latchbio/.venv/lib/python3.10/site-packages/latch_cli/main.py", line 282, in local_execute
    from latch_cli.services.local_execute import local_execute
  File "/home/jvfe/dev/latchbio/.venv/lib/python3.10/site-packages/latch_cli/services/local_execute.py", line 7, in <module>
    from latch_cli.services.register import RegisterCtx, _print_build_logs, build_image
ImportError: cannot import name '_print_build_logs' from 'latch_cli.services.register' (/home/jvfe/dev/latchbio/.venv/lib/python3.10/site-packages/latch_cli/services/register/__init__.py)

```

</details>
